### ISSUE TITLE
Request ID not transmitted in responses

### ISSUE THREAD

**Issue by d-plaindoux** [phimage/CallbackURLKit#6] opened 2016-08-20 10:27 UTC
When a response must be posted the corresponding requestID is missing in the returned URL

**Comment by phimage** [comment] 2016-08-20 12:44
I am working on #3 and I think it's the same problem
URL are not correctly encoded (some part must be, some other not, and there is some double encoding...) and query argument splitting failed

**Comment by d-plaindoux** [comment] 2016-08-20 12:50
Well after a debugging stage the requestID is correctly received but never transmitted in the the URL response. Therefor the request callbacks are not activated because this requestID is missing. 

I do a first Quick and Dirty fix in my source code with something in handleOpenURL method defined in Manager.swift like:
```swift
   if let requestID = parameters[kRequestID] {
       comp &= "\(kRequestID)=\(requestID)"
   }
```
and then every thing works fine. As a conclusion I think this problem is not related to the encoding one :-)

**Comment by phimage** [comment] 2016-08-20 12:57
Ok thanks for the information

**Comment by phimage** [comment] 2016-08-20 15:19
close as duplicate of #3 
Fix will be released soon

**Closed by phimage** 2016-08-20 15:19 UTC
Labels: bug, duplicate

**Comment by d-plaindoux** [comment] 2016-08-20 15:39
Hoops agree! When i read the URL I check the decoded parameters set instead of the original URL received by the manager. And since a requestId is unique I don't check this initial encoding i.e. abusive interpretation done by myself :-s 

Thanks
